platform: linux
inputs:
- name: git-repo
run:
  path: bash
  args:
    - -exc
    - |
      ${PWD}/git-repo/ci/scripts/vscode-extension-di-publish.sh
params:
  NPM_TOKEN_REPO_SPRING_IO: ((npm-token-repo-spring-io))
